[tool]
id = "io.github.anweaver23.scriptures"
label = "Scriptures"
versionCode = 1
versionName = "0.1.0"
permissions = []
capabilities = ["detached-audio", "tool-manager-provider"]
orientation = "portrait"
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
